version: '3.1'
services:
  db:
    hostname: mysql
    image: mysql:8.0.23
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - docker_network

  spring_project:
    hostname: ecommerce
    image: turalsadigov/ecommerce:v2
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION_IP: mysql
    networks:
      - docker_network

networks:
  docker_network:

volumes:
  db_data: