apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
  labels:
    app: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce
          image: turalsadigov/ecommerce:v16
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION_IP
              value: mysql